server:
  port: 2233

#security.jwt.token.secret-key: my-secret-key
#security:
jwt:
  secret: aziz-secret-key
  lifetime: 30m


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task-system
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  mvc:
    log-request-details: true

#logging:
#  level:
#    org.springframework.web: debug
#    org.hibernate.SQL: INFO
#  file:
#    name: D:/Aziz/jobs/EffectiveMobile/December/myapp.log

logging:
  level:
    org.springframework.web: debug
    org.hibernate.SQL: INFO
    org:
      springframework:
        security: DEBUG
