#Database
POSTGRES_SQL_USERNAME: azizdev
POSTGRES_SQL_PASSWORD: pass_sql
POSTGRES_SQL_HOST: postgresql
POSTGRES_SQL_PORT: 5433
POSTGRES_SQL_DB: postgres

#Server
SERVER_PORT: 2233
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <YOUR EMAIL>
EMAIL_PASSWORD: <YOUR GMAIL APP PASSWORD - NOT your email password>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}